spring.application.name=life-rpg-backend

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/life_rpg
spring.datasource.username=root
spring.datasource.password=Mysql@2026

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080